/*
 * Prak_P1.H
 *
 *  Created on: 19.04.2018
 *      Author: aml
 */

#ifndef PRAK_P1_H_
#define PRAK_P1_H_

namespace P1{

void P1A00();
void P1A01();
void P1A02();
void P1A03();
void P1A04();
void P1A05();
void P1A06();


unsigned short termValue(unsigned short bits);
unsigned short getBinValue(unsigned short v, char c);
unsigned short implies(unsigned short A, unsigned short B);
unsigned short logEq  (unsigned short A, unsigned short B);

}

#endif /* PRAK_P1_H_ */
