/*
 * V00.H
 *
 *  Created on: 17.04.2018
 *      Author: aml
 */

#ifndef V00_H_
#define V00_H_


void demoV00();

/*
 *
 * https://www.logisch-gedacht.de/logikraetsel/wer-hat-recht/
 *
 */

void TAML();
int TAMLeval1(int T, int A, int M, int L);
int TAMLeval2(int T, int A, int M, int L);
int TAMLeval3(int T, int A, int M, int L);

void A2L();
int  A2Leval(int A, int B, int C, int D, int E, int F, int G, int H, int I, int J, int K, int L);

int implies(int A, int B);
int logEq(int A, int B);





#endif /* V00_H_ */
