/*
 * V02.H
 *
 *  Created on: 01.05.2018
 *      Author: aml
 */

#ifndef V02_H_
#define V02_H_

namespace xml{
	void output(int i);
}

namespace str{
	void output(int i);
}

void myFunction(int i);

void swap(int    *a, int    *b);
void swap(float  *a, float  *b);
void swap(double *a, double *b);


void demoV02_Overload();
void demoV02_Namespace();
void demoV02_Exception();
void demoV02_StandardParam();
void demoV02_DynMem();
void demoV02_string();
void demoV02_refrence();




#endif /* V02_H_ */
